# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b4cf88e1e4e77261f54dcb9fd3c90d3bb484de19f62b89654e7238a41986b22202f7f70ed640b1f597da42ed84df41cf7b8442ae66c9ca6a6f7d7365ded197

test:
  secret_key_base: 4b61f7c67f96728320fe6ee610c84bef761d79dc87575dd7c32c9ff569d2801a8cc240b0e32389c85f3c9d4f93a40fcbe5415773f90d615aa652cfc527c51247

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
